### ISSUE TITLE
stylelint integration issues

### ISSUE THREAD

**Issue by patsissons** [webschik/postcss-less#14]
I got around to doing the `stylelint` integration tests today and saw that there is an issue with `mixin` parsing. `postcss-scss` parses their mixins as an `atrule` node, which is handled by the `postcss` stringifier. The solution is to either write a custom stringify function for `mixin` node, or fix the tokenizer to emit `atrule` nodes for mixins. Either choice is fine, but the latter may be easier (and is consistent with what is mentioned in the readme file).

Here is an example of a broken `LESS` snippet with respect to the stringifier:
```less
.for(@n: 1) when (@n <= 10) { .n-@{n} { content: %(\"n: %d\", 1 + 1); } .for(@n + 1); }
```

**Comment by patsissons** [comment]
There is also another integration issue but I'm not sure exactly how to resolve it. I believe the tokenization is correct, but the rule is matching on the `decl` node and failing because it thinks the outer parens are a function param block.

The following line is breaking the `function-whitespace-after` rule, expecting a space before the `em`. 
```less
h1 { max-height: ((@line-height) * (@lines-to-show))em; }
```

Open to suggestions on how to fix it.
